ERMS_System/urls.py
from core import views as core_views 
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from core.views import CustomLoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('core/logout', auth_views.LogoutView.as_view(), name='logout'),
    path('', include('core.urls',namespace='core')),
    path('records/', include('records.urls',namespace='records')),
    path('students/', include('students.urls', namespace='students')),
    path('academics/', include('academics.urls', namespace='academics')),
]

handler400 = 'core.views.error_400_view'
handler403 = 'core.views.error_403_view'
handler404 = 'core.views.error_404_view'
handler500 = 'core.views.error_500_view'

academics/urls.py
# academics/urls.py
from django.urls import path
from .import views

app_name = 'academics'

urlpatterns = [

    # path('<int:course_id>/', views.student, name='student'),
    path('department', views.department, name= "Department_dashboard"),
    path('add_department/', views.add_department, name='add_department'),
    path('<int:department_id>/update/', views.department_update, name='department_update'),
    path('<int:department_id>/delete/', views.department_delete, name='department_delete'),
    path('program/', views.program, name= "Program_dashboard"),
    path('add_program/', views.add_program, name='add_program'),
    path('program/<int:program_id>/update/', views.program_update, name='program_update'),
    path('program/<int:program_id>/delete/', views.program_delete, name='program_delete'),
    path('semesters/<int:program_id>/', views.semester_filtered, name='semester_filtered'),
    path('add_semester/', views.add_semester, name='add_semester'),
    path('semester/<int:semester_id>/update/', views.semester_update, name='semester_update'),
    path('semester/<int:semester_id>/delete/', views.semester_delete, name='semester_delete'),
    path('course/', views.course, name= "Course_dashboard"),
    path('add_course/', views.add_course, name='add_course'),
    path('course/<int:course_id>/update/', views.course_update, name='course_update'),
    path('course/<int:course_id>/delete/', views.course_delete, name='course_delete'),
    path('batch/', views.batch, name= "Batch_dashboard"),
    path('add_batch/', views.add_batch, name='add_batch'),
    path('batch/<int:batch_id>/update/', views.batch_update, name='batch_update'),
    path('batch/<int:batch_id>/delete/', views.batch_delete, name='batch_delete'),
 ]

core/urls.py
# core/urls.py
from django.urls import path
from . import views
from academics.views import department

app_name = 'core'

urlpatterns = [
    path('', views.dashboard, name='main_dashboard'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.Logout, name="Logout"),
    path('users/', views.users, name='users_dashboard'),
    path('user/create/', views.user_create, name='user_create'),
    path('user/update/<int:user_id>/', views.user_update, name='user_update'),
    path('user/delete/<int:user_id>/', views.user_delete, name='user_delete'),
    
    # path('about/', views.about, name='about'),
    # Add more URLs specific to your 'core' app as needed
]

records/urls.py
from django.urls import path
from . import views

app_name = 'records'

urlpatterns = [
    path('', views.exam_dashboard, name='Exam_dashboard'),
    path('dash', views.dash, name="results_dash"),
    path('add_record/', views.add_record, name='add_record'),
    path('batches/<int:exam_record_id>/', views.batches, name='batches'),
    path('update_batch/<int:id>/', views.update_batch, name="update_batch"),
    path('semesters/<int:batch_id>/<int:exam_record_id>/', views.semesters, name='semesters'),  
    path('courses/<int:semester_id>/<int:batch_id>/', views.courses, name='courses'),
    path('course/<int:course_id>/semester/<int:semester_id>/batch/<int:batch_id>/records/', views.course_student_records, name='course_student_records'),
    path('update_student_record/', views.update_student_record, name='update_student_record'),
    path('reset_student_record/', views.reset_student_record, name='reset_student_record'),
    path('records-dashboard', views.semesters_rec_dash, name='semester_record_dashboard'),
    path('batch/<int:exam_record_id>/', views.records_batches, name='records_batches'),
    path('semester/<int:batch_id>/<int:exam_record_id>/', views.records_semester, name='record_semester'),
    path('records/semester-results/<int:exam_record_id>/<int:semester_id>/<int:batch_id>/', views.semester_results, name='semester_results'),
    path('courses-records/', views.courses_rec_dash, name='courses_record_dashboard'),
    path('course-batch/<int:exam_record_id>/', views.course_records_batches, name='course_records_batches'),
    path('course-semester/<int:batch_id>/<int:exam_record_id>/', views.courses_semesters, name='courses_semesters'),
    path('courses-courses/<int:semester_id>/<int:batch_id>/', views.courses_record, name='courses_record'),
    path('course-results/<int:semester_id>/<int:batch_id>/<int:course_id>/', views.course_results, name='course_results'),
    path('transcript/program/', views.transcript_program_selection, name='Transcript_Program'),
    path('transcript/batch/<int:program_id>/', views.transcript_batch, name='Transcript_Batch'),
    path('transcript/students/<int:batch_id>/', views.transcript_student, name='Transcript_students'),
    path('transcript/<int:student_id>/', views.student_transcript, name='student_transcript'),
]

students/urls.py
# students/urls.py
from django.urls import path
from . import views



app_name = 'students'

urlpatterns = [
    # path('<int:course_id>/', views.student, name='student'),
    path('', views.student, name= "Student_dashboard"),
    # path('get_programs_and_batches/', get_programs_and_batches, name='get_programs_and_batches'),
    path('add_student/', views.add_student, name='add_student'),
    path('<int:student_id>/update/', views.student_update, name='student_update'),
    path('<int:student_id>/delete/', views.student_delete, name='student_delete')
]

    # path('add_student/', views.add_student, name='add_student'),

    # path('<int:id>/', views.student_detail, name='student_detail'),

templates/adminlte/lib/_main_footer.html
<footer class="main-footer">
        <div class="float-right d-none d-sm-block">
        {% block footer_right %}
            <b>Version</b> {% block version %}1.0 {% endblock %}
        {% endblock %}
    </div>

    {% block footer_left %}
    {% block legal %}
    <strong>Developed by Batch 20T (CS Department)  {% if not site %}{% endif %}</strong>
    {% endblock %}
    {% endblock %}
</footer>

templates/adminlte/lib/_main_header.html
{% load adminlte_helpers i18n %}
{% load static %}
<nav class="main-header navbar navbar-expand navbar-white navbar-light">


    <!-- Header Navbar: style can be found in header.less -->
    {% block nav_bar %}
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/" class="nav-link">Home</a>
        </li>
        {% if request.user.role == 'Admin' or request.user.role == 'Faculty' %}
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'admin:index' %}" class="nav-link">Admin</a>
        </li>
        {% endif %}
    </ul>
    {% block nav_custom_menu %}
    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <ul class="nav navbar-nav">
            {% block header_dropdowns %}
            {% block user_info %}
            {% if request.user.is_authenticated %}
            <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle="dropdown" href="#">
                        <i class="far fa-user fa-2x"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <a href="#" class="dropdown-item">
                            <!-- Message Start -->
                            <div class="media">
                                <img src="{%avatar_url size=128 %}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                                <div class="media-body">
                                    <h3 class="dropdown-item-title">
                                            {% firstof request.user.get_short_name request.user.get_username %}
                                        <span class="float-right text-sm text-danger"><i class="fas fa-online"></i></span>
                                    </h3>
                                    <p class="text-sm"><small>{% trans 'Member since' %} :</small></p>
                                    <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i>  <small>{{ request.user.date_joined }}</small></p>
                                </div>
                            </div>
                            <!-- Message End -->
                        </a>
                        <div class="dropdown-divider"></div>
                        <div class="dropdown-footer">
                            {% if request.user.role == 'Admin' or request.user.role == 'Faculty' %}
                                <a href="{% block change_password_url %}{% url 'admin:password_change' %}{% endblock %}" class="btn btn-primary btn-sm">{% trans 'Change password' %}</a>
                                {%endif%}
                                <a  href="{% block logout_url %}{% logout_url %}{% endblock %}" class="btn btn-danger btn-sm">{%trans 'Sign out'%}</a>
                            </div>
                        
                    </div>
                </li>
            {% endif %}
            {% endblock user_info %}
            {% endblock header_dropdowns %}
        </ul>
    </ul>
        {% endblock nav_custom_menu %}

{% endblock %}
</nav>

templates/adminlte/lib/_main_sidebar.html
{% load adminlte_helpers %}
{% load static %}
<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    {% block logo %}
        <a href="/" class="brand-link">
            {% block logo_text %}
            <span class="brand-text font-weight-black" style="display: block; text-align: center; width: 100%;">AWKUM EMS System</span>
            {% endblock %}
        </a>
    {% endblock %}
    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel -->
        {% block user_panel %}
        <div class="logo-panel mt-3 pb-3 mb-3 d-flex justify-content-center">
            <a href="/" class="brand-link" style="display: block; text-align: center;">
                <img src="{% static 'admin-lte\images\awkumlogo.png' %}" class="img-fluid" alt="AWKUM" style="max-height: 100px; display: inline-block;">
            </a>
        </div>
        {% endblock %}

        <!-- Sidebar menu -->
        {% block nav_links_ul %}
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                {% block nav_links_outer %}
                {% block nav_links %}
                <li class="nav-item">
                    <a href="{% url 'core:main_dashboard' %}" class="nav-link {% if request.resolver_match.url_name == 'main_dashboard' %}active{% endif %}">
                        <i class="nav-icon fas fa-home"></i>
                        <p>Dashboard</p>
                    </a>
                </li>

                {% with sub_menu_active=request.resolver_match.url_name|default_if_none:'' %}
                <!-- Academic Records Menu -->
                <li class="nav-item has-treeview {% if sub_menu_active in 'Department_dashboard Program_dashboard Semester_dashboard Course_dashboard Student_dashboard Batch_dashboard' %}menu-open{% endif %}">
                    <a href="#" class="nav-link {% if sub_menu_active in 'Department_dashboard Program_dashboard Semester_dashboard Course_dashboard Student_dashboard Batch_dashboard' %}active{% endif %}">
                        <i class="nav-icon fas fa-book"></i>
                        <p>
                            Academic Records
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        {% if request.user.role in 'Admin Faculty' %}
                        <li class="nav-item">
                            <a href="{% url 'academics:Department_dashboard' %}" class="nav-link {% if sub_menu_active == 'Department_dashboard' %}active{% endif %}">
                                <i class="nav-icon fas fa-building"></i>
                                <p>Departments</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'academics:Program_dashboard' %}" class="nav-link {% if sub_menu_active == 'Program_dashboard' %}active{% endif %}">
                                <i class="nav-icon fas fa-graduation-cap"></i>
                                <p>Programs</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'academics:Batch_dashboard' %}" class="nav-link {% if sub_menu_active == 'Batch_dashboard' %}active{% endif %}">
                                <i class="nav-icon fas fa-users"></i>
                                <p>Batches</p>
                            </a>
                        </li>
                        {% endif %}
                        <li class="nav-item">
                            <a href="{% url 'academics:Course_dashboard' %}" class="nav-link {% if sub_menu_active == 'Course_dashboard' %}active{% endif %}">
                                <i class="nav-icon fas fa-book"></i>
                                <p>Courses</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'students:Student_dashboard' %}" class="nav-link {% if sub_menu_active == 'Student_dashboard' %}active{% endif %}">
                                <i class="nav-icon fas fa-user-graduate"></i>
                                <p>Students</p>
                            </a>
                        </li>
                    </ul>
                </li>

                <!-- Examinations Menu -->
                <li class="nav-item has-treeview {% if sub_menu_active in 'results_dash Exam_dashboard semester_record_dashboard records_batches record_semester semester_results courses_record_dashboard course_records_batches courses_semesters courses_record course_results Transcript_Program Transcript_Batch Transcript_students student_transcript student_transcript_pdf' %}menu-open{% endif %}">
                    <a href="#" class="nav-link {% if sub_menu_active in 'results_dash Exam_dashboard semester_record_dashboard records_batches record_semester semester_results courses_record_dashboard course_records_batches courses_semesters courses_record course_results Transcript_Program Transcript_Batch Transcript_students student_transcript student_transcript_pdf' %}active{% endif %}">
                        <i class="nav-icon fas fa-clipboard"></i>
                        <p>
                            Examinations
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{% url 'records:Exam_dashboard' %}" class="nav-link {% if sub_menu_active == 'Exam_dashboard' %}active{% endif %}">
                                <i class="nav-icon fas fa-clipboard"></i>
                                <p>Exam Records</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'records:results_dash' %}" class="nav-link {% if sub_menu_active in 'semester_record_dashboard results_dash records_batches record_semester semester_results courses_record_dashboard course_records_batches courses_semesters courses_record course_results Transcript_Program Transcript_Batch Transcript_students student_transcript student_transcript_pdf' %}active{% endif %}">
                                <i class="nav-icon fas fa-clipboard-check"></i>
                                <p>Results</p>
                            </a>
                        </li>
                    </ul>  <!-- Close the nav-treeview ul here -->
                </li>

                {% if request.user.role in 'Admin Faculty' %}
                <li class="nav-item">
                    <a href="{% url 'core:users_dashboard' %}" class="nav-link {% if sub_menu_active == 'users_dashboard' %}active{% endif %}">
                        <i class="nav-icon fas fa-users"></i>
                        <p>Users Management</p>
                    </a>
                </li>
                {% endif %}
{% comment %}                 
                {% if request.user.role in 'Admin Faculty' %}
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-desktop"></i>
                        <p>Online Portal</p>
                    </a>
                </li>
                {% endif %} {% endcomment %}
                {% endwith %}
                {% endblock nav_links %}
                {% endblock nav_links_outer %}
            </ul>
        </nav>
        {% endblock nav_links_ul %}
    </div>
    <!-- /.sidebar -->
</aside>

templates/adminlte/lib/_messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
        <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
        </div>
        {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
        </div>
        {% else %}
        <div class="alert alert-info alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
        </div>
        {% endif %}
    {% endfor %}
{% endif %}

templates/adminlte/lib/_pagination.html
{% if pager and ROOT_MENU.current_menu.view_name %}
    <ul class="pagination pagination-sm no-margin pull-right">
        <li><a href="{% url ROOT_MENU.current_menu.view_name %}?page=1&{{ pager.url_params }}">&laquo;</a></li>
        {% if pager.page > 2 %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:-2}}&{{ pager.url_params }}">
                    {{ pager.page | add:-2 }}
                </a>
            </li>
        {% endif %}
        {% if pager.page > 1 %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:-1}}&{{ pager.url_params }}">
                    {{ pager.page | add:-1 }}
                </a>
            </li>
        {% endif %}
        <li class="active"><a href="#">{{ pager.page }}</a></li>
        {% if pager.has_next %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:1}}&{{ pager.url_params }}">
                    {{ pager.page | add:1 }}
                </a>
            </li>
        {% endif %}
        {% if pager.has_next_two %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:2}}&{{ pager.url_params }}">
                    {{ pager.page | add:2 }}
                </a>
            </li>
        {% endif %}
        <li>
            <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.last_page}}&{{ pager.url_params }}">
            &raquo;
            </a>
        </li>
    </ul>
{% endif %}

templates/adminlte/lib/_scripts.html
{% load static %}

{% block scripts %}
<script src="{% static 'admin-lte/plugins/jquery/jquery.min.js' %}"></script>
<script src="{% static 'admin-lte/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>
<script src="{% static 'admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js' %} "></script>


{% block datatable_js %}{% endblock %}

<script src="{% static 'admin-lte/dist/js/adminlte.min.js' %}"></script>
<script src="{% static 'admin-lte/dist/js/demo.js' %}"></script>
{% endblock %}

templates/adminlte/lib/_styles.html
{% load static %}

{% block styles %}
<!-- Font Awesome -->
<link rel="stylesheet" href="{% static 'admin-lte/plugins/fontawesome-free/css/all.min.css' %}">
<!-- Ionicons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'admin-lte/dist/css/adminlte.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'admin-lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
{% endblock %}